name: Create new release with attachments on each push
on: [push]
jobs:
  compile_files:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Set up environment
      run: |
        sudo apt-get update && \
        sudo apt-get install -y python3-pip && \
        sudo -H pip3 install pillow
    - name: Run data building scripts
      run: |
        ./scripts/summary.py block.js.gz"
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::$(date +"%Y-%m-%d_%H-%M-%S")"
    - name: Publish release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload summary.txt to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: summary.txt
        asset_name: summary.txt
        tag: ${{ steps.tag.outputs.release_tag }}
        overwrite: true
    - name: Upload summary.png to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: summary.png
        asset_name: summary.png
        tag: ${{ steps.tag.outputs.release_tag }}
        overwrite: true
    - name: Upload blocked_accounts.txt.gz to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: blocked_accounts.txt.gz
        asset_name: blocked_accounts.txt.gz
        tag: ${{ steps.tag.outputs.release_tag }}
        overwrite: true
